Update ci.yml
fix:   warning • The asset file '.env.dev' doesn't exist. Try creating the file or fixing the path to the file • pubspec.yaml:85:7 • asset_does_not_exist
  warning • The asset file '.env.prod' doesn't exist. Try creating the file or fixing the path to the file • pubspec.yaml:86:7 • asset_does_not_exist

  2 issues found. (ran in 15.5s)
  Error: Process completed with exit code 1.

name: Create env stubs
run: touch .env.dev .env.prod